###
POST http://localhost:3000/add
Content-Type: application/json

{
  "name": "pen",
  "price": 5000
}

###
GET http://localhost:3000/show

###
DELETE http://localhost:3000/delete/66ffc12b41b417444ac9ab27

###
DELETE http://localhost:3000/deleteall